### ISSUE TITLE
simplex noise

### ISSUE THREAD

**Issue by CaoYuanpu** [Julian-Wyatt/AnoDDPM#10]
I was wondering why the simplex noise depends on the diffusion timestep t in rand_3d_fixed_T_octaves().

**Comment by Julian-Wyatt** [comment]
Hi,
Yes this was a minor experiment although I’m fairly sure no images generated in the paper use that function.
I was considering testing a 3D noise function where the depth of the image is the timestep in the diffusion process, but there wasn’t enough stochasticity to learn from I felt.
Hopefully that helps

**Comment by CaoYuanpu** [comment]
Hi,
Thanks for replying. But it looks like you use it in generate_simplex_noise(), which is the default for noise_fn='simplex'.
Another question is I was wondering what specific simplex noise you used for MVTEC leather dataset, rand_2d_octaves()?
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/42167703/222181451-d5667379-f34e-4a2c-90f6-2118c3adab3a.png">

**Comment by Julian-Wyatt** [comment]
I think in general I used a 3D simplex noise function due to the directional artefacts I mention on line 112.
For that there's no massively important depth slice to use so I just kept it as being dependent on t; although in theory, I feel it should work if you pick any random slice if you shuffle the seed each time.
