### ISSUE TITLE
Datasets Question

### ISSUE THREAD

**Issue by WilliamJudge94** [Julian-Wyatt/AnoDDPM#12]
Hello,

I am trying to run this repo with the same data as presented in the paper in order to gain a baseline understanding of this diffusion model. However, I am having trouble setting up the datasets. For the datasets:

1. Are these the links for the training and test sets?

- a. Training to be placed in  ./DATASETS/Train directory: http://preprocessed-connectomes-project.org/NFB_skullstripped/
- b. Testing to be placed in ./DATASETS/CancerousDataset/EdinburghDataset/Anomalous-T1/raw directory : https://reshare.ukdataservice.ac.uk/851861/

2. There are a lot of .tar files within the Testing dataset (if that link is correct). Did you decompress the files, open the individual datasets and save them as a .npy file?

3. Will the files have to be read and saved to .npy files within these directories?

4. Do you have a detailed folder structure and file format we need to use in order to get your code working?

**Comment by Julian-Wyatt** [comment]
1. Yeah exactly those however I think the testing data is now closed or locked as others have since reported.
2. Again, yes exactly, it was more efficient to open the file with the library in python (can't remember the name of it, I must import it in my datasets.py file) and then save the processed images as npy files.
3. If you want to handle this the same as I did, I wrote a directory scraper to loop over all the files and save them - although don't believe I uploaded that with this repository. 
4. I've uploaded a screenshot of a minimal case. The datasets.py file should loop through the contents of those directories as the training, test and anomalous data sources. 
<img width="420" alt="Screenshot 2023-03-26 at 16 01 30" src="https://user-images.githubusercontent.com/44175667/227784548-ba5db42f-4138-4113-a799-92c38aeb72a0.png">


If you have any further questions, please let me know
