### ISSUE TITLE
some doubts about the principle of the diffusion model

### ISSUE THREAD

**Issue by jamdodot** [Julian-Wyatt/AnoDDPM#15]
Why does the noise addition and denoising process not destroy the normal part, but “assimilate” the abnormal part into the normal part.  Because the model remembers the features of the normal part while training? Then the reasoning process destroys and transforms the abnormal part？

**Comment by Julian-Wyatt** [comment]
You've pretty much answered your own question.

This is a common method for unsupervised anomaly detection. Where we have a generator which is trained to generate healthy images. So when we encode a new unlabelled image; in theory if it was anomalous it would be decoded such that the model "imagines" what it would look like if it was healthy. Then we can deduce areas of high reconstruction error are consequently anomalous. 
So yes, in short, it is because the "encoding" by the forward process learns what noise is in healthy images, but when reversing this process any anomaly would be considered as part of this noise and removed in the denoising process.
