### ISSUE TITLE
some questions about DDPM

### ISSUE THREAD

**Issue by ZHEGG** [Julian-Wyatt/AnoDDPM#17]
thanks for your nice code, I am a beginner in the field of diffusion and hope to learn more through your code，I have some questions during my learning process and hope you can help me.
1、When running your open-source code, I set the 'vis_img' switch to true, expecting to see the images of xt-1 and x0，However, I have some doubts about the images displayed. Why is the image of Xt-1/sample clearer than that of X0/pred_x0? Moreover, I noticed that when using 'vis_img', the noise was set to torch.rand_like, while for 'vis_video', the noise was sampled by noise_fn. Would this cause a difference in the images? Here are my results
![image](https://github.com/Julian-Wyatt/AnoDDPM/assets/65839993/3651dbd4-73c9-47c8-88fc-4d904228ee3c)

I hope you can help me, thanks!!!

**Comment by Julian-Wyatt** [comment]
Hi,


1. 
<img width="827" alt="Screenshot 2023-06-15 at 11 45 48" src="https://github.com/Julian-Wyatt/AnoDDPM/assets/44175667/5a66c8bf-302e-476d-82b3-d5e9c09eb318">
There are different outputs depending on the epoch; the one you have highlighted outputs, the real, $x_{t-1}$ and a prediction of $x_0$. Whereas the other outputs real, image with noise, prediction of noise and the mse of the two. 

2. You are correct; this was a minor mistake and was not swapped once I moved to Simplex noise, due to not needing to output the images then. This also does seem to correlate to the strange samples on the screen - For the images I generated for the paper, I used the generate_images.py file to generate my samples rather than these training images.
