### ISSUE TITLE
Encountered Access Issue of E-mail

### ISSUE THREAD

**Issue by Jonathan-fzq** [Julian-Wyatt/AnoDDPM#26]
Dear Julian,

I hope this message finds you well. I am a student specializing in anomaly detection at Lanzhou University of Technology. 
I attempted to contact you through your email address julian.wyatt@durham.ac.uk, but unfortunately, I encountered access issues. In order to ensure that I can get in touch with you, I am reaching out via this method. I appreciate your understanding.

If it's convenient for you, please feel free to reply to this message, or provide an alternative contact method where I can reach you. 
I have been following your work on the AnoDDPm model with great interest. I kindly request your assistance in obtaining the checkpoints of the AnoDDPm model. Access to these checkpoints would significantly benefit my research and help me better understand its implementation.

I deeply appreciate your contributions to the field and would be grateful for your support. Rest assured, I will use the resources responsibly and provide proper attribution.

Thank you for your time and consideration.

Sincerely,
Zhiqiang Feng 
Lanzhou University of Technology
jonathan_fzq@163.com

**Comment by Julian-Wyatt** [comment]
Hi Jonathan,
Yeah I graduated from Durham not long after the publication, and am now at oxford, you would be best to discuss things here ideally. 
I'm not overly keen on providing checkpoints - due to the size of them and using the online storage - I'm not even sure I still have them; however with that said, I am more than happy to help you to replicate the work to see if you can make additional progress?
Cheers,
Julian
